name: sid-germany

channels:
  - conda-forge
  - opensourceeconomics
  - pytask

dependencies:
  - python>=3.7
  - pip

  - conda-build

  - black
  - dask
  - estimagic>=0.0.29
  - fastparquet
  - jupyterlab
  - nodejs
  - numba
  - numpy
  - pandas>=1,<1.1
  - pdbpp
  - pre-commit
  - pytask >=0.0.9
  - pytask-parallel
  - pytask-latex
  - pytest
  - python-snappy
  - scipy
  - seaborn
  - snakeviz
  - xlrd

  - sphinx
  - pydata-sphinx-theme
  - nbsphinx
  - pip:
    - DFO-LS
    - Py-BOBYQA
